### ISSUE TITLE
Building astroid in Ubuntu 14.04

### ISSUE THREAD

**Issue by mohz** [gauteh/astroid#110]
Hello,

in the wiki "Compiling and installing" for Ubuntu (https://github.com/gauteh/astroid/wiki/Ubuntu) several dependencies are listed. While trying to install astroid on Ubuntu 14.04 I ran into the issue that **libsass-dev** is not available for 14.04 due to several dependency issues. What am I missing?

Thank you.
M

**Comment by gauteh** [comment]
Maybe somebody else here are using Ubuntu and know this better, but you
need libsass including dev. I'd search for other people having issues with
the package on ubuntu. I assume you tried installing all the deps for
libsass-dev?

Den onsdag 30. mars 2016 skrev mohz <notifications@github.com> følgende:

**Comment by mohz** [comment]
Alright, which distro are you using? For me this isn't a major issue: Ubuntu is only a stepping stone, however I think it woul be appropriate to change the wiki.

<blockquote> On a <b>fresh Ubuntu 14.04</b> the following was required to get astroid going... </blockquote>

is simple misleading because Ubuntu 15.10 (Wily) offers libsass. I will test it on a live system and we can close the issue.

**Comment by gauteh** [comment]
OK. Im using Arch Linux. Maybe the wiki should read 'on a recent ubuntu'?

Den onsdag 30. mars 2016 skrev mohz <notifications@github.com> følgende:

**Comment by gauteh** [comment]
Did you figure this one out?

**Comment by mohz** [comment]
Not yet, having trouble getting my computer to work with Ubuntu...

**Comment by PartyPoster** [comment]
Hi guys, some input on this because I ran into the same issue.

I tried installing libsass manually on 14.04 yesterday and couldn't get it to go.  The package depends on some of the Standard C/C++ libraries that are only available in Ubuntu 15.10 so I'm assuming this is the reason libsass has been left out of 14.04.  If you tried to updating all of the dependencies there is a good chance you're going to break a lot of things (plus it would be a lot of work).

I ended up just upgrading to 15.10 but I don't think this would be too much of a deal breaker for many people because Astroid would generally be installed on a desktop, so sticking to the LTS release isn't as big of a deal.

I would recommend just updating the wiki to say Ubuntu 15.10 or later, since that is the only version of Ubuntu that has libsass-dev available.

**Comment by mohz** [comment]
Hi @PartyPoster!

Thanks for joining in. Yes, your recommendation is definitely the way to go, but I wanted to test it out before changing the wiki. Still without success, but since it you have it running with 15.10 we can close this issue (and update the wiki.)

**Comment by gauteh** [comment]
Great, thanks! Hope you get it running.. weird that libsass-dev is not available in 14.
