### ISSUE TITLE
drafts not tagged as draft

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#111]
When I save a new message as a draft, it will be marked as a draft (with the right tag) and with the red message saying I can edit it with 'E'

But if I close astroid and open it again, this message will not be tagged 'draft' any more.

Can you reproduce this?

(workaround: the message is saved in the right Draft folder and thus I open mutt, hit 'm' and it suggests to open the draft)

**Comment by gauteh** [comment]
Could this be a synchronization issue between notmuch and your imap client? If astroid tags the message as a draft something has to remove the draft tag again. It could be that because the maildirflags are not synced that notmuch removes the draft tag if the message is moved/renamed by the IMAP client (in that case it is related to #31).

**Comment by hugoroy** [comment]
0. Activate plane mode to make sure no syncing happens with offlineimap
1.  Open a new message in Vim, write and then :wq
2. Hit Save draft (s)

    Result: the message is now with the 'draft' tag 

3. Quit astroid
4. Open astroid: The message is still marked as draft and can be edited. Everything looks fine.
5. Activate online mode
6. offlineimap -o
7. The draft tag has disappeared

Spot on!

**Comment by gauteh** [comment]
Note that as a workaround you can add the draft tag manually, in astroid, and you should be able to open it as a draft.
