### ISSUE TITLE
Mark threads more efficiently

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#144]
Currently, if one wants to mark tens of threads one has to press `t` and an arrow key for each thread. It would be more efficient if one could press and hold `t` in order to mark threads downwards. Same with `T` in the upwards direction. I would propose to use `y` to unmark a thread.

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 21, 2016 23:51:
> Currently, if one wants to mark tens of threads one has to press `t` and an arrow key for each thread. It would be more efficient if one could press and hold `t` in order to mark threads downwards. Same with `T` in the upwards direction. I would propose to use `y` to unmark a thread.

`t` now moves to next thread by deafult. There are also unbound targets
for:

thread_index.toggle_marked_next=t (new behaviour)
thread_index.toggle_marked (which is the previous behaviour)
thread_index.toggle_marked_previous (toggles and moves to previous)

I do not think it is necessary with a unmark key since all the others
toggle the state. If you want to unmark all the marked threads press +
and t.
