### ISSUE TITLE
(documentation) how to "poll"?

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#32]
I see keybindings for polling and I see a poll.sh in "examples/" but I don't get how to configure polling.

For me, polling is just about running `offlineimap -o` but where do I configure that?

**Comment by gauteh** [comment]
This is poorly documented,

When pressing 'P' or setting up automatic polling in the config the
script ~/.config/astroid/poll.sh is run. As you can see from the example
I usually run offlineimap and then notmuch new. Astroid will check for
correct exit status and use that before checking for any changes.

So to set up a poll script, make the script: ~/.config/astroid/poll.sh,
set it executable and press 'P' in astroid. The output from the script
is logged in Astroid as well.

Automatic polling is controlled by "poll.interval", and is specified in
seconds, I typically use 160.

Since I am using gmail for some of my accounts I am using abunchoftags
[1] with a fancier poll.sh [2], but you don't need that.

[1] https://github.com/gauteh/abunchoftags
[2] https://github.com/gauteh/abunchoftags/blob/master/examples/fetch_and_sync.sh

Hugo Roy writes on January 3, 2016 18:36:
