### ISSUE TITLE
Scrolling up log output in tmux window freezes UI in some cases

### ISSUE THREAD

**Issue by ff2000** [gauteh/astroid#54]
I use tmux in urxvt.
I found one specific hint when the ui freezes: open threads that get scrolled completely to the bottom when opened. Look for threads that do and for some that don't scroll to the bottom, then try:
1) scroll the log up
2) open threads in astroid
3) see it freeze/not freeze the UI depending on scrollbar position
The UI will unfreeze as soon as you scroll down the log.
I can't reproduce this without tmux.
I also had freezes when opening a new search, but I couldn't find a reliable way to reproduce this issue.

**Comment by gauteh** [comment]
Interesting. I think this happens when the log tries to flush to stdout
or stderr, but the pipe to tmux is probably blocking.

I know one other situation, where astroid freezes: If a Db write
operation is to be done and the notmuch db is locked. For instance, if
you try to archive a thread while notmuch new is running in the
background. Then astroid will freeze untill notmuch new is done and the
db lock is released.

Does these freezes last or do they unfreeze once you scroll down in tmux
again?

**Comment by ff2000** [comment]
They unfreeze as soon I scroll down in tmux.

**Comment by gauteh** [comment]
try compiling with:

$ scons --enable-debug=no

that should fix it. otherwise I will keep it since flushing the output
means I can get the last logs even if astroid crashes.
